CONNECTION_URL=jdbc:mysql://localhost:3306/mercato_ortofrutticolo_db
LOGIN_USER=login
LOGIN_PASS=login
SEGRETERIA_USER=segreteria
SEGRETERIA_PASS=segreteria
GESTORE_MAGAZZINO_USER=gestore_magazzino
GESTORE_MAGAZZINO_PASS=gestore_magazzino
